services:
  aosp6:
    build:
      context: .
      dockerfile: Dockerfile
    image: q20-aosp6:24.04
    platform: linux/amd64
    volumes:
      - .:/workspace/project
    working_dir: /workspace/project
    command: /bin/bash
    stdin_open: true
    tty: true
